package org.researchstack.sampleapp.bridge.body;
public class SharingOptionBody
{
    /**
     * One of three string values:
     * <li><b>no_sharing:</b> Don't share data generated by this participant;</li>
     * <li><b>sponsors_and_partners:</b> share data in data sets that are available to the study
     * researchers and their researcher partners only</li>
     * <li><b>all_qualified_researchers:</b> Share data with researchers who qualify under the
     * specific governance qualifications to access the study's data set. These researchers may do
     * research on new questions after the lifetime of the initial research</li>
     */
    private String scope;

    public SharingOptionBody(String scope)
    {
        this.scope = scope;
    }
}
